//! Cross-language wire vectors: every CBOR/sig surface that crosses the
//! Dart↔Rust boundary, pinned in the canonical
//! `app/starling/test/vectors/index.json` (regenerated by the phone's
//! `test/vectors/vectors_gen.dart`; asserted on the Dart side by
//! `vectors_test.dart`).
//!
//! Dart-produced surfaces (pairing claim, PushBatch, EncryptedEvent) are
//! DECODED here; Rust-produced surfaces (PairResponse, RelayQrCard,
//! ManifestPage, MediaManifestPage, PushReceipt, the /events Envelope) are
//! asserted byte-for-byte against this crate's encoders. The
//! `manifest_ack` entry is Dart↔Dart only and intentionally not covered.

use base64::Engine;
use serde_json::Value;
use starling_wire::delete::{DeleteEventsRequest, DeleteMediaRequest, DeleteReceipt};
use starling_wire::event_header::EncryptedEventHeader;
use starling_wire::manifest::{
    ManifestEntry, ManifestPage, MediaManifestPage, StatusJson, VoiceStatusJson,
};
use starling_wire::pairing::{
    compute_pair_claim, relay_id, PairResponse, PairingClaimWire, RelayQrCard,
};
use starling_wire::push::{PushBatch, PushReceipt};
use starling_wire::voice::{VoiceSlotPush, VoiceSlotReceipt};
use starling_wire::{
    crockford_base32_decode, crockford_base32_encode, owner_request_digest, verify_ed25519,
    verify_owner_request_sig, verify_owner_sig, PROTOCOL_VERSION,
};

fn vectors() -> Value {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../../app/starling/test/vectors/index.json"
    );
    let text = std::fs::read_to_string(path).expect("read app/starling/test/vectors/index.json");
    serde_json::from_str(&text).expect("parse vectors json")
}

fn rw(vectors: &Value) -> &Value {
    &vectors["relay_wire"]
}

fn unhex(v: &Value) -> Vec<u8> {
    hex::decode(v.as_str().expect("hex string")).expect("valid hex")
}

fn owner_pk(vectors: &Value) -> [u8; 32] {
    unhex(&vectors["keypair"]["ed25519_public_key_hex"])
        .try_into()
        .unwrap()
}

/// F3: the Rust and Dart version constants both pin to the SAME vector
/// entry, so a one-sided bump fails the other side's tests.
#[test]
fn protocol_version_pins_to_shared_vector_entry() {
    let v = vectors();
    assert_eq!(
        PROTOCOL_VERSION,
        v["protocol_version"].as_str().expect("protocol_version entry")
    );
}

#[test]
fn crockford_base32_matches_dart() {
    let v = vectors();
    let c = &rw(&v)["crockford_base32"];
    let bytes = unhex(&c["bytes_hex"]);
    assert_eq!(
        crockford_base32_encode(&bytes),
        c["encoded"].as_str().unwrap()
    );
    assert_eq!(
        crockford_base32_decode(c["lookalike_decode_input"].as_str().unwrap()),
        crockford_base32_decode(c["lookalike_decode_canonical"].as_str().unwrap()),
    );
}

#[test]
fn pair_claim_digest_sig_and_cbor_decode() {
    let v = vectors();
    let c = &rw(&v)["pair_claim"];
    let pk = owner_pk(&v);
    let token = unhex(&c["pairing_token_hex"]);
    let onion = c["admin_onion"].as_str().unwrap();

    let digest = compute_pair_claim(&pk, onion, &token);
    assert_eq!(hex::encode(digest), c["claim_digest_hex"].as_str().unwrap());

    let sig = unhex(&c["sig_hex"]);
    assert!(verify_ed25519(&pk, &digest, &sig));

    // The Dart-encoded claim body decodes to the expected wire struct.
    let body = unhex(&c["claim_cbor_hex"]);
    let wire: PairingClaimWire = ciborium::from_reader(&body[..]).expect("decode claim cbor");
    assert_eq!(
        wire.owner_pubkey,
        base64::engine::general_purpose::STANDARD.encode(pk)
    );
    assert_eq!(wire.pairing_token, token);
    assert_eq!(wire.sig, sig);
}

#[test]
fn relay_id_and_pair_response_encode() {
    let v = vectors();
    let c = &rw(&v)["relay_id"];
    let pk = owner_pk(&v);
    let onion = c["owner_onion"].as_str().unwrap();
    let rid = relay_id(&pk, onion);
    assert_eq!(rid, c["relay_id_hex"].as_str().unwrap());

    let resp = PairResponse {
        relay_onion: onion.to_string(),
        relay_id: rid,
    };
    let mut buf = Vec::new();
    ciborium::into_writer(&resp, &mut buf).unwrap();
    assert_eq!(buf, unhex(&c["pair_response_cbor_hex"]));
}

#[test]
fn relay_qr_card_encode() {
    let v = vectors();
    let c = &rw(&v)["relay_qr_card"];
    let claim = &rw(&v)["pair_claim"];
    let card = RelayQrCard {
        relay_onion: claim["admin_onion"].as_str().unwrap().to_string(),
        pairing_token: unhex(&claim["pairing_token_hex"]),
        relay_version: c["relay_version"].as_str().unwrap().to_string(),
    };
    let mut buf = Vec::new();
    ciborium::into_writer(&card, &mut buf).unwrap();
    assert_eq!(buf, unhex(&c["cbor_hex"]));
}

#[test]
fn encrypted_event_header_decodes() {
    let v = vectors();
    let c = &rw(&v)["encrypted_event"];
    let header = EncryptedEventHeader::parse(&unhex(&c["cbor_hex"])).expect("parse header");
    assert_eq!(header.pubkey, c["pubkey"].as_str().unwrap());
    assert_eq!(header.created_at, c["created_at"].as_i64().unwrap());
    assert_eq!(header.epoch, c["epoch"].as_i64().unwrap());
    assert_eq!(header.msg_seq, c["msg_seq"].as_i64().unwrap());
    assert_eq!(header.nonce.len(), 24);
}

#[test]
fn push_batch_decodes_and_owner_sig_verifies() {
    let v = vectors();
    let c = &rw(&v)["push_batch"];
    let body = unhex(&c["cbor_hex"]);
    let batch = PushBatch::parse(&body).expect("parse push batch");
    assert_eq!(batch.items.len(), 1);
    assert_eq!(batch.items[0].id, c["event_id"].as_str().unwrap());
    assert_eq!(
        batch.items[0].payload,
        unhex(&rw(&v)["encrypted_event"]["cbor_hex"])
    );
    // X-Starling-Sig: Ed25519 over blake2b256(body).
    assert!(verify_owner_sig(
        &owner_pk(&v),
        &body,
        &unhex(&c["owner_sig_hex"])
    ));
}

/// F4: a Dart-produced batch carrying a non-"event" item type decodes with
/// the type preserved (and the untyped batch still defaults to "event").
#[test]
fn typed_push_batch_decodes_with_type_preserved() {
    let v = vectors();
    let c = &rw(&v)["push_batch_typed"];
    let batch = PushBatch::parse(&unhex(&c["cbor_hex"])).expect("parse typed batch");
    assert_eq!(batch.items.len(), 1);
    assert_eq!(batch.items[0].id, c["item_id"].as_str().unwrap());
    assert_eq!(batch.items[0].item_type, c["item_type"].as_str().unwrap());
    assert_eq!(batch.items[0].payload, unhex(&c["payload_hex"]));

    // The untyped vector defaults to "event".
    let untyped = PushBatch::parse(&unhex(&rw(&v)["push_batch"]["cbor_hex"])).unwrap();
    assert_eq!(untyped.items[0].item_type, "event");
}

/// Phase 3: the Dart-produced `POST /events/delete` body decodes, and its
/// request-bound signature (M2 domain) verifies at the pinned timestamp.
#[test]
fn delete_events_request_decodes_and_bound_sig_verifies() {
    let v = vectors();
    let c = &rw(&v)["delete_events_request"];
    let body = unhex(&c["cbor_hex"]);
    let req = DeleteEventsRequest::parse(&body).expect("parse delete events request");
    let expected_ids: Vec<&str> = c["ids"]
        .as_array()
        .unwrap()
        .iter()
        .map(|i| i.as_str().unwrap())
        .collect();
    assert_eq!(req.ids, expected_ids);

    let ts = c["signed_ts"].as_i64().unwrap();
    let path = c["signed_path"].as_str().unwrap();
    let digest = owner_request_digest("POST", path, ts, &body);
    assert_eq!(hex::encode(digest), c["owner_req_digest_hex"].as_str().unwrap());
    assert!(verify_owner_request_sig(
        &owner_pk(&v),
        "POST",
        path,
        ts,
        &body,
        &unhex(&c["owner_sig_hex"]),
    ));
    // …and the same signature fails on any other path (domain binding).
    assert!(!verify_owner_request_sig(
        &owner_pk(&v),
        "POST",
        "/media/delete",
        ts,
        &body,
        &unhex(&c["owner_sig_hex"]),
    ));
}

#[test]
fn delete_media_request_decodes() {
    let v = vectors();
    let c = &rw(&v)["delete_media_request"];
    let req = DeleteMediaRequest::parse(&unhex(&c["cbor_hex"])).expect("parse delete media");
    let expected: Vec<&str> = c["hashes"]
        .as_array()
        .unwrap()
        .iter()
        .map(|h| h.as_str().unwrap())
        .collect();
    assert_eq!(req.hashes, expected);
}

/// The Rust-produced DeleteReceipt must emit the pinned bytes the Dart
/// decoder reads.
#[test]
fn delete_receipt_encode() {
    let v = vectors();
    let c = &rw(&v)["delete_receipt"];
    let receipt = DeleteReceipt {
        deleted: c["deleted"].as_i64().unwrap(),
        missing: c["missing"].as_i64().unwrap(),
    };
    assert_eq!(receipt.to_cbor(), unhex(&c["cbor_hex"]));
}

#[test]
fn push_receipt_encode() {
    let v = vectors();
    let c = &rw(&v)["push_receipt"];
    let receipt = PushReceipt {
        accepted: c["accepted"].as_i64().unwrap(),
        rejected: c["rejected"].as_i64().unwrap(),
    };
    assert_eq!(receipt.to_cbor(), unhex(&c["cbor_hex"]));
}

#[test]
fn manifest_page_encode() {
    let v = vectors();
    let c = &rw(&v)["manifest_page"];
    let page = ManifestPage {
        pubkey: v["event_id"]["pubkey"].as_str().unwrap().to_string(),
        events: vec![ManifestEntry {
            id: v["event_id"]["id_base32"].as_str().unwrap().to_string(),
            created_at: 1_700_000_000,
        }],
        has_older: true,
    };
    assert_eq!(page.to_cbor(), unhex(&c["cbor_hex"]));
}

#[test]
fn media_manifest_page_encode() {
    let v = vectors();
    let c = &rw(&v)["media_manifest_page"];
    let page = MediaManifestPage {
        hashes: vec!["aa".repeat(32), "bb".repeat(32)],
        has_older: false,
    };
    assert_eq!(page.to_cbor(), unhex(&c["cbor_hex"]));
}

/// Plan 20: the Dart-produced `POST /voice/rooms` body decodes (including
/// the optional per-slot cap), its blinded hashes match blake2b256 of the
/// never-pushed preimage, and the request-bound signature verifies.
#[test]
fn voice_slot_push_decodes_and_bound_sig_verifies() {
    let v = vectors();
    let c = &rw(&v)["voice_slot_push"];
    let body = unhex(&c["cbor_hex"]);
    let push = VoiceSlotPush::parse(&body).expect("parse voice slot push");
    assert_eq!(push.slots.len(), 2);
    assert_eq!(push.slots[0].token_hash, unhex(&c["token_hash_hex"]));
    assert_eq!(push.slots[0].max_participants, Some(8));
    assert_eq!(push.slots[1].token_hash, unhex(&c["token2_hash_hex"]));
    assert_eq!(push.slots[1].max_participants, None);
    // The slot is blinded: hash of the preimage a joiner will present.
    assert_eq!(
        starling_wire::blake2b256(&unhex(&c["token_hex"])).to_vec(),
        push.slots[0].token_hash
    );

    let ts = c["signed_ts"].as_i64().unwrap();
    let path = c["signed_path"].as_str().unwrap();
    let digest = owner_request_digest("POST", path, ts, &body);
    assert_eq!(hex::encode(digest), c["owner_req_digest_hex"].as_str().unwrap());
    assert!(verify_owner_request_sig(
        &owner_pk(&v),
        "POST",
        path,
        ts,
        &body,
        &unhex(&c["owner_sig_hex"]),
    ));
}

/// The Rust-produced VoiceSlotReceipt must emit the pinned bytes.
#[test]
fn voice_slot_receipt_encode() {
    let v = vectors();
    let c = &rw(&v)["voice_slot_receipt"];
    let receipt = VoiceSlotReceipt { slots: c["slots"].as_i64().unwrap() };
    assert_eq!(receipt.to_cbor(), unhex(&c["cbor_hex"]));
}

/// `GET /status` including the always-present `voice` object (Plan 20).
#[test]
fn status_json_encode_includes_voice() {
    let v = vectors();
    let c = &rw(&v)["status_json"];
    let status = StatusJson {
        pubkey: c["json"]["pubkey"].as_str().unwrap().to_string(),
        version: c["json"]["version"].as_str().unwrap().to_string(),
        event_count: 1,
        storage_used: 2048,
        storage_limit: 0,
        media_storage_used: 1024,
        voice: VoiceStatusJson { enabled: true, max_participants: 12, slot_count: 2 },
    };
    assert_eq!(serde_json::to_value(&status).unwrap(), c["json"]);
}

#[test]
fn events_envelope_encode() {
    let v = vectors();
    let c = &rw(&v)["events_envelope"];
    let payload = unhex(&rw(&v)["encrypted_event"]["cbor_hex"]);
    let bytes = starling_wire::envelope::build_events_envelope(
        c["version"].as_str().unwrap(),
        vec![payload.as_slice()],
    );
    assert_eq!(bytes, unhex(&c["cbor_hex"]));
}
